# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f66697ccdd1e0560c110511d0dc70e62051a6298be966aa43e7be1630249dcd8cd52e5947f48f27e6b1e188a7c634d3bd0f4c92dbc550455cb1052f7c6a0c8a6

test:
  secret_key_base: 9ac88834de5480b70d33a1cd7dc1f1947229e66bb4811a2e5ae9efdc228c1a75c39465d128ef4fb5dfed260132b5740d54cb47885befc048b2c3cc0d48850f94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
